on:
  push:
    tags:        
      - '*'

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: -p expunge_derive

      - uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: -p expunge
            #book:
            #  name: Build mdbook
            #  runs-on: ubuntu-latest
            #  steps:
            #    - uses: actions/checkout@v2
            #    - uses: actions-rs/toolchain@v1
            #      with:
            #        profile: minimal
            #        toolchain: stable
            #        override: true
            #    - uses: actions-rs/cargo@v1
            #      with:
            #        command: install
            #        args: mdbook
            #    - uses: actions-rs/cargo@v1
            #      with:
            #        command: mdbook
            #        args: build -d public
            #      artifacts:
            #        paths:
            #          - public
